# Generated by Django 4.2.3 on 2023-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Здесь должен быть текст', max_length=255, verbose_name='текст')),
                ('files', models.FileField(upload_to='../tempVideo/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
