# Generated by Django 4.2.3 on 2023-07-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(help_text='Здесь должен быть текст', max_length=209, verbose_name='текст'),
        ),
    ]
